### PR TITLE
mark as done & user images

### PR DESCRIPTION
**Pull request by RonaTross**
@yonbergman @maximveksler - you guys can look at this new branch when you get to the cr

### CODE REVIEW

**Comment by yonbergman** [comment]
Please include screenshots and/or Gifs 
Here's a great tool to capture gifs on a mac - http://www.cockos.com/licecap/

**Comment by yonbergman** [comment]
Also since you still haven't merged that other branch. We need to make sure to open this PR to the other branch. right now it includes all the commits of pr #3 too

**Comment by RonaTross** [comment]
Demo: 
techtalksdemo

**Comment by RonaTross** [comment]
sete

**Pull request merged**
